import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
        >
          {/* header */}
            <main className="min-h-screen">{children}</main>
        </ThemeProvider>
        <footer className="text-center text-sm text-gray-500 dark:text-gray-400 py-4">
          © {new Date().getFullYear()} Carrier Guide by Sunny. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
